# ==============================================
# 🛠️ POLARIS MARKETING - DEVELOPMENT SETUP
# ==============================================
# Development Docker Compose with hot reload

version: '3.8'

services:
  marketing-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: polaris-marketing-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_URL=http://localhost:3002
      - NEXT_PUBLIC_PLATFORM_URL=http://localhost:3001
      - NEXT_PUBLIC_MARKETING_URL=http://localhost:3000
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    networks:
      - dev-network
    command: npm run dev

networks:
  dev-network:
    driver: bridge
