# ==============================================
# 🚀 POLARIS MARKETING - STANDALONE DEPLOYMENT
# ==============================================
# Independent Docker Compose for Marketing App

version: '3.8'

services:
  # 🏪 Marketing Website
  marketing:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: polaris-marketing
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-https://api.polarisplatform.ch}
      - NEXT_PUBLIC_PLATFORM_URL=${NEXT_PUBLIC_PLATFORM_URL:-https://app.polarisplatform.ch}
      - NEXT_PUBLIC_MARKETING_URL=${NEXT_PUBLIC_MARKETING_URL:-https://polarisplatform.ch}
      # Email configuration
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_SECURE=${SMTP_SECURE:-false}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - EMAIL_FROM=${EMAIL_FROM:-noreply@polarisplatform.ch}
      # Google Sheets configuration
      - GOOGLE_SHEETS_CLIENT_EMAIL=${GOOGLE_SHEETS_CLIENT_EMAIL}
      - GOOGLE_SHEETS_PRIVATE_KEY=${GOOGLE_SHEETS_PRIVATE_KEY}
      - GOOGLE_SHEETS_SHEET_ID=${GOOGLE_SHEETS_SHEET_ID}
    env_file:
      - .env.local
    restart: unless-stopped
    networks:
      - marketing-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.marketing.rule=Host(`polarisplatform.ch`) || Host(`www.polarisplatform.ch`)"
      - "traefik.http.routers.marketing.tls=true"
      - "traefik.http.routers.marketing.tls.certresolver=letsencrypt"
      - "traefik.http.services.marketing.loadbalancer.server.port=3000"
      - "service.name=marketing"

networks:
  marketing-network:
    driver: bridge

# Optional: Nginx reverse proxy for standalone deployment
  # nginx:
  #   image: nginx:alpine
  #   container_name: marketing-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - marketing
  #   restart: unless-stopped
  #   networks:
  #     - marketing-network
